# Pip install numpy ---to install numpy library

In [3]:
import numpy as np #importing the library

# Create arrays

In [5]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


# 2D and 3D arrays

In [9]:
arr2d = np.array([[1,2,3],[4,5,6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr3d = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
arr3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

# Array properties

In [12]:
print(arr2d.ndim)

2


In [14]:
print(arr2d.shape)

(2, 3)


In [15]:
print(arr2d.size)

6


In [16]:
print(arr2d.dtype)

int64


# Array creation and functions

In [18]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [22]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [23]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [25]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
np.random.rand(2,3)

array([[0.9691411 , 0.0734125 , 0.62131721],
       [0.63460197, 0.07811988, 0.61661976]])

# Array indexing and slicing

In [32]:
arr=np.array([10,20,30,40,50])
print(arr[1:4])

[20 30 40]


In [37]:
arr2d = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr2d[0,1])   
print(arr2d[1:, :2])

20
[[40 50]
 [70 80]]


# Array operations

In [38]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [39]:
print(a+b)
print(a*b)
print(a**2)

[5 7 9]
[ 4 10 18]
[1 4 9]


# Universal functions

In [43]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [44]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [45]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])

# Statistical & Mathematical Functions

In [46]:
arr=np.array([1,2,3,4,5])

In [50]:
print(np.mean(arr)) 

print(np.median(arr))

print(np.std(arr))   

print(np.var(arr))  

print(np.min(arr))

print(np.max(arr))  

print(np.sum(arr))

3.0
3.0
1.4142135623730951
2.0
1
5
15


# Reshaping

In [52]:
arr = np.arange(1,10)
reshaped = arr.reshape(3,3)
print(reshaped)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Broadcasting

In [54]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([1,2,3])
print(a + b)

[[2 4 6]
 [5 7 9]]


# Boolean Indexing & Filtering

In [56]:
arr=np.array([10,20,30,40,50])
print(arr[arr > 25])
      

[30 40 50]


# Linear algebra

In [57]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [58]:
print(np.dot(A, B))
print(np.linalg.det(A))
print(np.linalg.inv(A)) 

[[19 22]
 [43 50]]
-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


# Real data science example

In [59]:
data = np.random.randn(1000)

# Compute statistics
mean = np.mean(data)
std = np.std(data)
z_scores = (data - mean) / std

print(f"Mean: {mean:.2f}, Std: {std:.2f}")

Mean: 0.05, Std: 0.97


# Find missing values in numpy

In [60]:
arr = np.array([1, np.nan, 3, np.nan])
np.isnan(arr)

array([False,  True, False,  True])

# Combine arrays

In [62]:
# np.concatenate([a,b])
# np.vstack((a,b))
# np.hstack((a,b))

# To get unique elements

In [63]:
arr = np.array([1,2,2,3,3,4])
np.unique(arr)

array([1, 2, 3, 4])

# Extract all even numbers

In [64]:
arr = np.array([1,2,3,4,5,6,7,8,9])
even = arr[arr % 2 == 0]
print(even)

[2 4 6 8]


# Replace all odd no in an array with -1

In [65]:
arr = np.arange(10)
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


# Stack two numpy arrays vertically and horizontally

In [66]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

# Vertical stack
v = np.vstack((a,b))

# Horizontal stack
h = np.hstack((a,b))

In [67]:
v

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [68]:
h

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

# Find dot product of two matrices

In [70]:
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[1,2],
              [3,4],
              [5,6]])

result = np.dot(A, B)
print(result)

[[22 28]
 [49 64]]


# How to find percentile values

In [71]:
arr = np.array([10,20,30,40,50])
p25 = np.percentile(arr, 25)
p50 = np.percentile(arr, 50)
p75 = np.percentile(arr, 75)

In [76]:
p25

np.float64(20.0)

In [73]:
p50

np.float64(30.0)

In [74]:
p75

np.float64(40.0)

# Check if two NumPy arrays are equal

In [77]:
a = np.array([1,2,3])
b = np.array([1,2,3])
print(np.array_equal(a,b))

True
