In [1]:
nums=[22,15,18,21,26,30,40]
for num in nums:
    if num % 5 == 0:
        print(num)

15
30
40


In [2]:
nums = [12,14,18,21,25,30,35]

for num in nums:
    if num % 5 == 0:
        print(num)  

25
30
35


In [3]:
nums = [12,14,18,21,25,20]

for num in nums:
    if num % 5 == 0:
        print(num)  

25
20


In [4]:
nums = [12,14,18,21,20,25]

for num in nums:
    if num % 5 == 0:
        print(num)  
        break

20


In [5]:
nums = [10,14,18,21,5,10]

for num in nums:
    if num % 5 == 0:
        print(num)  
        break #it will print only 1 number then it break        

10


In [6]:
nums = [7,14,18,21,23,27] #hear there is no number which is divisible by 5 we got output as blank

for num in nums:
    if num % 5 == 0:
        print(num)  
        break

In [7]:
nums = [7,14,18,21,23,27,29] #hear there is no number which is divisible by 5 we got output as blank

for num in nums:
    if num % 5 == 0:
        print(num)  
        break
    else:
        print('Number nhi mila bhaiiii ') #every iteration it cheking condition        

Number nhi mila bhaiiii 
Number nhi mila bhaiiii 
Number nhi mila bhaiiii 
Number nhi mila bhaiiii 
Number nhi mila bhaiiii 
Number nhi mila bhaiiii 
Number nhi mila bhaiiii 


In [8]:
nums = [7,14] #hear there is no number which is divisible by 5 we got output as blank
for num in nums:
    if num % 5 == 0:
        print(num)  
        break
    else:
        print('Number nhi mila') #every iteration it cheking condition        

Number nhi mila
Number nhi mila


In [9]:
nums = [7,14,18,21,23,27] #hear there is no number which is divisible by 5 we got output as blank

for num in nums:
    if num % 5 == 0:
        print(num)  
        break
else:
        print('Number Not Found') # hear else we dont write in if block but we can write in for block only

Number Not Found


In [10]:
nums = [10,14,18,21,20,27] #hear there is no number which is divisible by 5 we got output as blank

for num in nums:
    if num % 5 == 0:
        print(num)  
        break
else:
        print('Not Found')

10


In [11]:
nums = [10,14,18,21,20,27,30] #hear there is no number which is divisible by 5 we got output as blank

for num in nums:
    if num % 5 == 0:
        print(num)  
        #break
else:
        print('Not Found')

10
20
30
Not Found


In [12]:
nums = [10,14,18,21,20,27] #hear there is no number which is divisible by 5 we got output as blank
for num in nums:
    if num % 5 == 0:
        print(num)  
        break
else:
        print('Not Found')

10


# Prime number

In [13]:
num = 14

for i in range(2,num):
    if num % i == 0:
        print('Not prime Number')
        break
else:
    print('Prime Number')

Not prime Number


In [14]:
num = 13

for i in range(2,num):
    if num % i == 0:
        print('Not prime Number')
        break
else:
    print('Prime Number')

Prime Number


# Array in python

In [15]:
from array import * 
arr = array('i',[])

n = int(input('Enter the length of the array'))

for i in range(5):
    x = int(input('Enter the next value'))
    arr.append(x)
print(arr)

Enter the length of the array 5
Enter the next value 2
Enter the next value 1
Enter the next value 4
Enter the next value 3
Enter the next value 9


array('i', [2, 1, 4, 3, 9])


In [18]:
from array import * 
arr = array('i',[])

n = int(input('Enter the length of the array'))

for i in range(5):
    x = int(input('Enter the next value'))
    arr.append(x)
print(arr)

Enter the length of the array 1
Enter the next value 2
Enter the next value 3
Enter the next value 4
Enter the next value 2
Enter the next value 3


array('i', [2, 3, 4, 2, 3])


In [19]:
from array import * 
arr = array('i',[])

n = input('Enter the length of the array')

for i in range(5):
    x = input('Enter the next value')
    arr.append(x)
print(arr)

Enter the length of the array 2
Enter the next value 1


TypeError: 'str' object cannot be interpreted as an integer

# Way to creating aeeay using numpy

In [20]:
from numpy import *
arr = array([1,2,3,4,5])
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [21]:
print(arr.dtype)

int64


In [22]:
arr = array([1,2,3,4,5.9])
print(arr)

[1.  2.  3.  4.  5.9]


In [23]:
print(arr.dtype)

float64


In [24]:
arr2 = array([1,2,3,4,5.9],float)
arr2

array([1. , 2. , 3. , 4. , 5.9])

In [25]:
arr3 = array([1,2,3,4,5.6],int)
arr3

array([1, 2, 3, 4, 5])

In [26]:
import numpy as np

In [27]:
arr4 = np.linspace(0, 16, 10) # break the code between 10 spaces between 0 to 16 but why decimal becuase we break into parts thats why it is floats
arr4

array([ 0.        ,  1.77777778,  3.55555556,  5.33333333,  7.11111111,
        8.88888889, 10.66666667, 12.44444444, 14.22222222, 16.        ])

In [28]:
arr5 = np.arange(0,10,2) # arange - as range
arr5

array([0, 2, 4, 6, 8])

In [29]:
arr6 = np.zeros(5)
arr6

array([0., 0., 0., 0., 0.])

In [30]:
arr7 = np.ones(5)
arr7

array([1., 1., 1., 1., 1.])