In [1]:
#NUMPY ---> library which we are using dataanlytics , business analytic , ai , datascience , every where it required 

In [2]:
# what is array ---> collection of homogenous elements
#1d array, 2d array and nd---> multi dimensional array

In [3]:
#numpy is a library which handle multidimensional array and using numpy we can convr [ text to array, image to array, video to array]

In [4]:
#data is 2 part   1) strurcture data excel sheet and 2)unstrcured data text,audio,video,pdf,xml 

In [ ]:
#first off all we need to import numpy

In [7]:
import sys

In [8]:
sys.version

'3.13.5 | packaged by Anaconda, Inc. | (main, Jun 12 2025, 16:37:03) [MSC v.1929 64 bit (AMD64)]'

In [9]:
import numpy as np

In [10]:
np.__version__

'2.1.3'

In [11]:
#create a list

In [12]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [13]:
type(my_list)

list

In [14]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [15]:
type(arr)

numpy.ndarray

In [16]:
print(type(arr))
print(type(my_list))

<class 'numpy.ndarray'>
<class 'list'>


In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [20]:
np.arange(10,30,3)

array([10, 13, 16, 19, 22, 25, 28])

In [99]:
np.arange(10,20,30,3)

TypeError: Cannot interpret '3' as a data type

In [100]:
np.arange(8,20)

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [101]:
np.arange(20,8)

array([], dtype=int64)

In [102]:
np.arange(-20,8) #1st argument < 2nd argumnet

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7])

In [103]:
n=np.arange(-20,8)
n

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7])

In [104]:
np.zeros(3)

array([0., 0., 0.])

In [105]:
np.zeros(3,dtype=int)

array([0, 0, 0])

In [106]:
z=np.zeros(5)
z

array([0., 0., 0., 0., 0.])

In [107]:
np.zeros((2,2)) #2d array (two)

array([[0., 0.],
       [0., 0.]])

In [108]:
np.zeros((3,3), dtype=int) 

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [109]:
nd=np.zeros((5,9),dtype=int)  #ND ARRAY MILTI-D ARRAY

In [110]:
nd

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [111]:
np.ones(3)

array([1., 1., 1.])

In [112]:
np.ones(3,int)

array([1, 1, 1])

In [113]:
nd1=np.ones((10,10),int)
nd1

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [114]:
nd1=np.twice((10,10),int)
nd1

AttributeError: module 'numpy' has no attribute 'twice'

In [115]:
nd1

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [116]:
arr

array([0, 1, 2, 3, 4, 5])

In [117]:
z

array([0., 0., 0., 0., 0.])

In [118]:
nd

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [119]:
my_list

[0, 1, 2, 3, 4, 5]

In [120]:


                                                           # 04th july 2025




In [121]:
rand(3,2)

NameError: name 'rand' is not defined

In [122]:
random.rand

<bound method RandomState.rand of RandomState(MT19937) at 0x247D243BB40>

In [123]:
np.random.rand(2) 

array([0.14713825, 0.01787865])

In [124]:
np.random.rand(3) 

array([0.69377768, 0.64732156, 0.46734988])

In [125]:
np.random.rand(2,3)

array([[0.15209317, 0.4702235 , 0.94086648],
       [0.48065292, 0.69952537, 0.13964118]])

In [126]:
np.random.randint(3) #it grnertatee random int interval with higer exclusive

0

In [127]:
np.random.randint(5)

1

In [128]:
np.random.randint(2,10) #2 iclusive 10 is exclusive

3

In [129]:
np.random.randint(2, 10 ,3)

array([9, 7, 4], dtype=int32)

In [130]:
np.random.randint(-30,20,10)

array([-26,   5,  13, -30, -27,   9,  -6,   6,   3,  -3], dtype=int32)

In [131]:
np.random.randint(10,40,(10,10))

array([[36, 23, 23, 28, 31, 29, 11, 11, 13, 31],
       [39, 24, 16, 12, 15, 36, 13, 12, 21, 27],
       [24, 30, 20, 19, 18, 20, 33, 14, 25, 37],
       [23, 14, 18, 25, 27, 34, 13, 38, 13, 35],
       [12, 18, 12, 26, 26, 22, 16, 37, 37, 35],
       [19, 23, 29, 39, 25, 35, 28, 21, 29, 19],
       [32, 23, 13, 37, 15, 22, 24, 21, 37, 36],
       [22, 23, 15, 33, 39, 15, 16, 13, 19, 23],
       [29, 13, 28, 12, 21, 22, 32, 27, 33, 18],
       [31, 18, 29, 28, 26, 30, 17, 22, 23, 20]], dtype=int32)

In [132]:
m=np.random.randint(10,40,(10,10))
m

array([[39, 29, 14, 22, 26, 34, 31, 22, 15, 14],
       [25, 13, 12, 37, 23, 18, 26, 20, 33, 14],
       [18, 37, 36, 25, 20, 11, 33, 22, 19, 33],
       [15, 28, 34, 15, 17, 31, 29, 21, 39, 19],
       [11, 24, 12, 28, 37, 24, 20, 30, 16, 38],
       [13, 13, 26, 24, 25, 30, 28, 31, 21, 34],
       [22, 39, 39, 14, 11, 38, 18, 22, 23, 15],
       [19, 23, 15, 12, 27, 13, 28, 21, 13, 25],
       [25, 36, 22, 38, 31, 35, 32, 39, 35, 25],
       [12, 13, 20, 33, 21, 15, 35, 10, 36, 29]], dtype=int32)

In [133]:
arr

array([0, 1, 2, 3, 4, 5])

In [134]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [135]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [136]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [137]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [138]:
#slicing in matrix

In [139]:
m

array([[39, 29, 14, 22, 26, 34, 31, 22, 15, 14],
       [25, 13, 12, 37, 23, 18, 26, 20, 33, 14],
       [18, 37, 36, 25, 20, 11, 33, 22, 19, 33],
       [15, 28, 34, 15, 17, 31, 29, 21, 39, 19],
       [11, 24, 12, 28, 37, 24, 20, 30, 16, 38],
       [13, 13, 26, 24, 25, 30, 28, 31, 21, 34],
       [22, 39, 39, 14, 11, 38, 18, 22, 23, 15],
       [19, 23, 15, 12, 27, 13, 28, 21, 13, 25],
       [25, 36, 22, 38, 31, 35, 32, 39, 35, 25],
       [12, 13, 20, 33, 21, 15, 35, 10, 36, 29]], dtype=int32)

In [140]:
b=np.random.randint(10,40,(10,10))
b

array([[20, 32, 25, 34, 13, 29, 24, 37, 27, 11],
       [25, 33, 15, 22, 32, 32, 39, 13, 29, 34],
       [17, 25, 37, 12, 29, 13, 24, 30, 18, 35],
       [18, 15, 25, 19, 24, 12, 34, 33, 20, 28],
       [13, 18, 27, 23, 25, 14, 19, 32, 29, 27],
       [11, 18, 31, 38, 35, 35, 13, 18, 32, 38],
       [13, 12, 11, 19, 23, 35, 38, 36, 25, 38],
       [32, 10, 22, 25, 15, 31, 33, 16, 38, 35],
       [38, 10, 22, 37, 39, 14, 39, 33, 22, 32],
       [20, 27, 36, 35, 36, 16, 15, 22, 11, 28]], dtype=int32)

In [141]:
b[:]

array([[20, 32, 25, 34, 13, 29, 24, 37, 27, 11],
       [25, 33, 15, 22, 32, 32, 39, 13, 29, 34],
       [17, 25, 37, 12, 29, 13, 24, 30, 18, 35],
       [18, 15, 25, 19, 24, 12, 34, 33, 20, 28],
       [13, 18, 27, 23, 25, 14, 19, 32, 29, 27],
       [11, 18, 31, 38, 35, 35, 13, 18, 32, 38],
       [13, 12, 11, 19, 23, 35, 38, 36, 25, 38],
       [32, 10, 22, 25, 15, 31, 33, 16, 38, 35],
       [38, 10, 22, 37, 39, 14, 39, 33, 22, 32],
       [20, 27, 36, 35, 36, 16, 15, 22, 11, 28]], dtype=int32)

In [142]:
b[1:4]

array([[25, 33, 15, 22, 32, 32, 39, 13, 29, 34],
       [17, 25, 37, 12, 29, 13, 24, 30, 18, 35],
       [18, 15, 25, 19, 24, 12, 34, 33, 20, 28]], dtype=int32)

In [143]:
b[-1:]

array([[20, 27, 36, 35, 36, 16, 15, 22, 11, 28]], dtype=int32)

In [144]:
b[:-1]

array([[20, 32, 25, 34, 13, 29, 24, 37, 27, 11],
       [25, 33, 15, 22, 32, 32, 39, 13, 29, 34],
       [17, 25, 37, 12, 29, 13, 24, 30, 18, 35],
       [18, 15, 25, 19, 24, 12, 34, 33, 20, 28],
       [13, 18, 27, 23, 25, 14, 19, 32, 29, 27],
       [11, 18, 31, 38, 35, 35, 13, 18, 32, 38],
       [13, 12, 11, 19, 23, 35, 38, 36, 25, 38],
       [32, 10, 22, 25, 15, 31, 33, 16, 38, 35],
       [38, 10, 22, 37, 39, 14, 39, 33, 22, 32]], dtype=int32)

In [145]:
b

array([[20, 32, 25, 34, 13, 29, 24, 37, 27, 11],
       [25, 33, 15, 22, 32, 32, 39, 13, 29, 34],
       [17, 25, 37, 12, 29, 13, 24, 30, 18, 35],
       [18, 15, 25, 19, 24, 12, 34, 33, 20, 28],
       [13, 18, 27, 23, 25, 14, 19, 32, 29, 27],
       [11, 18, 31, 38, 35, 35, 13, 18, 32, 38],
       [13, 12, 11, 19, 23, 35, 38, 36, 25, 38],
       [32, 10, 22, 25, 15, 31, 33, 16, 38, 35],
       [38, 10, 22, 37, 39, 14, 39, 33, 22, 32],
       [20, 27, 36, 35, 36, 16, 15, 22, 11, 28]], dtype=int32)

In [146]:
b[:-1]

array([[20, 32, 25, 34, 13, 29, 24, 37, 27, 11],
       [25, 33, 15, 22, 32, 32, 39, 13, 29, 34],
       [17, 25, 37, 12, 29, 13, 24, 30, 18, 35],
       [18, 15, 25, 19, 24, 12, 34, 33, 20, 28],
       [13, 18, 27, 23, 25, 14, 19, 32, 29, 27],
       [11, 18, 31, 38, 35, 35, 13, 18, 32, 38],
       [13, 12, 11, 19, 23, 35, 38, 36, 25, 38],
       [32, 10, 22, 25, 15, 31, 33, 16, 38, 35],
       [38, 10, 22, 37, 39, 14, 39, 33, 22, 32]], dtype=int32)

In [147]:
b[:-2]

array([[20, 32, 25, 34, 13, 29, 24, 37, 27, 11],
       [25, 33, 15, 22, 32, 32, 39, 13, 29, 34],
       [17, 25, 37, 12, 29, 13, 24, 30, 18, 35],
       [18, 15, 25, 19, 24, 12, 34, 33, 20, 28],
       [13, 18, 27, 23, 25, 14, 19, 32, 29, 27],
       [11, 18, 31, 38, 35, 35, 13, 18, 32, 38],
       [13, 12, 11, 19, 23, 35, 38, 36, 25, 38],
       [32, 10, 22, 25, 15, 31, 33, 16, 38, 35]], dtype=int32)

In [148]:
b[1:4]

array([[25, 33, 15, 22, 32, 32, 39, 13, 29, 34],
       [17, 25, 37, 12, 29, 13, 24, 30, 18, 35],
       [18, 15, 25, 19, 24, 12, 34, 33, 20, 28]], dtype=int32)

In [149]:
b[1,2]

np.int32(15)

In [150]:
b

array([[20, 32, 25, 34, 13, 29, 24, 37, 27, 11],
       [25, 33, 15, 22, 32, 32, 39, 13, 29, 34],
       [17, 25, 37, 12, 29, 13, 24, 30, 18, 35],
       [18, 15, 25, 19, 24, 12, 34, 33, 20, 28],
       [13, 18, 27, 23, 25, 14, 19, 32, 29, 27],
       [11, 18, 31, 38, 35, 35, 13, 18, 32, 38],
       [13, 12, 11, 19, 23, 35, 38, 36, 25, 38],
       [32, 10, 22, 25, 15, 31, 33, 16, 38, 35],
       [38, 10, 22, 37, 39, 14, 39, 33, 22, 32],
       [20, 27, 36, 35, 36, 16, 15, 22, 11, 28]], dtype=int32)

In [151]:
b[1,7]

np.int32(13)

In [152]:
b[1,3]

np.int32(22)

In [153]:
b

array([[20, 32, 25, 34, 13, 29, 24, 37, 27, 11],
       [25, 33, 15, 22, 32, 32, 39, 13, 29, 34],
       [17, 25, 37, 12, 29, 13, 24, 30, 18, 35],
       [18, 15, 25, 19, 24, 12, 34, 33, 20, 28],
       [13, 18, 27, 23, 25, 14, 19, 32, 29, 27],
       [11, 18, 31, 38, 35, 35, 13, 18, 32, 38],
       [13, 12, 11, 19, 23, 35, 38, 36, 25, 38],
       [32, 10, 22, 25, 15, 31, 33, 16, 38, 35],
       [38, 10, 22, 37, 39, 14, 39, 33, 22, 32],
       [20, 27, 36, 35, 36, 16, 15, 22, 11, 28]], dtype=int32)

In [154]:
b[1,-1]

np.int32(34)

In [155]:
#numpy operations

In [156]:
arr

array([0, 1, 2, 3, 4, 5])

In [157]:
arr.max()

np.int64(5)

In [158]:
arr.min()

np.int64(0)

In [159]:
from numpy import *
a=array[(1,2,3,4,5,9)]
median (a)

TypeError: 'builtin_function_or_method' object is not subscriptable

In [160]:
mat=np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [161]:
row=4
col=5

In [162]:
col

5

In [163]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [164]:
mat[1] #how to print rows

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [165]:
mat[:,col] #how to print col

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [166]:
mat[:,3]

array([ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93])

In [167]:
mat[3]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [168]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [169]:
mat[::,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [170]:
mat[::-2]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [171]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [172]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [173]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [174]:
mat[1:2,2:4] 

array([[12, 13]])

In [175]:
mat[3:5,2:4] 

array([[32, 33],
       [42, 43]])

In [176]:
# masking or filter

In [177]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [178]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [179]:
mat [mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [180]:
mat [mat>=50]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [181]:
mat [mat==50]

array([50])

In [182]:
mat [mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [183]:
mat [mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [184]:
mat [mat!=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [185]:
mat [mat==99]

array([99])